version: '2'

services:
  mysql:
    image: rworksjp/mysql-osc-2016-tokyo-spring
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql:/var/lib/mysql
    env_file: .env

  pandora_console:
    image: rworksjp/pandora_console-osc-2016-tokyo-spring
    build: ./pandora_console
    ports:
      - "80:80"
    links:
      - mysql
    env_file: .env

  pandora_server:
    image: rworksjp/pandora_server-osc-2016-tokyo-spring
    build: ./pandora_server
    hostname: pandora_server
    ports:
      - "41121:41121"
    links:
      - mysql
      - chromedriver
    env_file: .env

  pandora_agent:
    image: rworksjp/pandora_agent-osc-2016-tokyo-spring
    build: ./pandora_agent
    hostname: pandora_agent
    ports:
      - "3000:3000"
    links:
      - pandora_server

  chromedriver:
    image: rworksjp/chromedriver-osc-2016-tokyo-spring
    build: ./chromedriver
    ports:
      - "5900:5900"
    env_file: .env

networks:
  default:
    driver: bridge
