mysql:
  hostname: mysql
  container_name: mysql
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - /opt/mysql:/var/lib/mysql
  env_file: .env

pandora_console:
  hostname: pandora_console
  build: ./pandora_console
  ports:
    - "80:80"
  links:
    - mysql
  env_file: .env

pandora_server:
  build: ./pandora_server
  hostname: pandora_server
  ports:
    - "41121:41121"
  links:
    - mysql
  env_file: .env

pandora_agent:
  build: ./pandora_agent
  hostname: pandora_agent
  links:
    - pandora_server
